name: Gerar Datas

on:
  schedule: # executar a cada 12 hora
    - cron: "* */12 * * *"
  workflow_dispatch: 
  
jobs:
  build:
    name: Atualizar Datas
    runs-on: ubuntu-latest
    steps:
      # Animação da Cobra
      # - uses: Platane/snk@master
      #   id: snake-gif
      #   with:
      #     github_user_name: GabrielaCS13
      #     svg_out_path: dist/github-contribution-grid-snake.svg

      # gera um jogo da cobra a partir do gráfico de contribuições de um usuário do GitHub (<github_user_name>), produzindo uma animação SVG em <svg_out_path>
      - name: Gerar github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=blue&color_dots=#40E0D0,#48D1CC,#00CED1,#20B2AA,#008080
            
    

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
